var info = {
    "nombre" : "Faviola",
    "edad" : "18",
    "direccion" : "san martin de la priramides",
    "gustos" :{
        "comida" :{
            "tacos dorados" : true,
            "salchi pulpos" : true,
            "arroz" : true,
        },
        "seies" :{
            "teen wolf" : true,
            "scorpion" : true,
            "the good doctor" : true,
        },
        "hobbies" :{
            "paper craft" : true,
            "dibujo digital" : true,
            "leer manga" : true,
        },
        "animes" :{
            "bleach" : true,
            "kengan ashura" : true,
            "parasyte" : true,
        },
        "familia" : {
            "mama" : true,
            "hermana" :true,
        }
    }

}
console.log(info);